module VerifyExamples.Internal.Utils.AvgLength0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Internal.Utils exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#avgLength: \n\n    avgLength [[1], [1, 2], [1, 2, 3]]\n    --> 2" <|
        \() ->
            Expect.equal
                (
                avgLength [[1], [1, 2], [1, 2, 3]]
                )
                (
                2
                )