module VerifyExamples.Internal.Utils.AvgLength1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Internal.Utils exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#avgLength: \n\n    avgLength [[1], [1], [1]]\n    --> 1" <|
        \() ->
            Expect.equal
                (
                avgLength [[1], [1], [1]]
                )
                (
                1
                )