module VerifyExamples.Internal.Utils.MinLength0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Internal.Utils exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#minLength: \n\n    minLength [[1], [1, 2], [1, 2, 3]]\n    --> 1" <|
        \() ->
            Expect.equal
                (
                minLength [[1], [1, 2], [1, 2, 3]]
                )
                (
                1
                )